### ISSUE TITLE
MYSTRAN description by SteveDoyle2

### ISSUE THREAD

**Issue by drbillcase** [SteveDoyle2/MYSTRAN#1]
As the original author of MYSTRAN, the description of it should more properly read: "MYSTRAN is a General Purpose Finite Element Structural Analysis Computer Program developed by Dr Bill Case". The source code is distributed by NASA under their Open Source Software Agreement. The executable, and documentation, can also be downloaded from Dr Case's web site, www.MYSTRAN.com

**Comment by SteveDoyle2** [comment]
Not a problem.  I was a bit unclear though on exactly what you had in mind, so if that's not it, let me know.

**Comment by drbillcase** [comment]
Thanks Steve but I am not sure what it is that you are unclear about. I was
just attempting to explain what my program was about

**Comment by SteveDoyle2** [comment]
Does the page look like what you wanted?

**Comment by drbillcase** [comment]
I just looked at it and can't see any change. Am I missing something?
Sorry, but I'm really not trying to be a problem

**Comment by drbillcase** [comment]
I just looked at the page and I can't see any change. Sorry, but I am not
trying to be difficult - just thought what I wrote was a better description
than your 1st line under MYSTRAN on the GitHub page.

**Comment by SteveDoyle2** [comment]
I know.  Sorry if I was/seemed short.  I had a 14 hour workday yesterday and probably was :)  I'm more than happy to give you credit for what you did.

The description section is the 1-liner at the very top, which I updated yesterday.  I think that's maybe where the confusion came from.

I just put the entire block that you requested in the Introduction section.

**Comment by drbillcase** [comment]
Thanks Steve. I appreciate it. Good luck with your  project. Not many
groups have liked Fortran but it was the choice of scientists and engineers
for a long time back when I was working and still may be.

Bill

**Comment by SteveDoyle2** [comment]
Thanks.  Fortran is definitely still used.  I learned Fortran 77 back in April of this year to do some work with Abaqus.   It's a lot nicer than C++.  The VAX stuff confuses me though, so porting old stuff is tricky.
